---
# tasks file for tomcat10
- name: check if playbook is being executed on supported OS
  ansible.builtin.fail:
    msg: "This playbook is design to work on ubuntu & redhat only"
  when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "RedHat"
- name: run redhat specific tasks
  ansible.builtin.include_tasks:
    file: redhat.yaml
  when: ansible_facts['distribution'] == "RedHat"
- name: run ubuntu specific tasks
  ansible.builtin.include_tasks:
    file: ubuntu.yaml
  when: ansible_facts['distribution'] == "Ubuntu"
- name: run common tasks
  ansible.builtin.include_tasks:
    file: common.yaml