---
- name: install iis & chrome on windows
  hosts: all
  tasks:
    - name: enable iis server
      win_feature:
        name: Web-Server
        include_management_tools: yes
        state: present
    - name: install chrome
      win_package:
        path: https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7BFB0E1252-04B3-103E-2E54-C9EBC90A4757%7D%26lang%3Den-GB%26browser%3D4%26usagestats%3D1%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-statsdef_1%26brand%3DCHBD%26installdataindex%3Dempty/update2/installers/ChromeSetup.exe
        state: present
        validate_certs: no