---
- name: install lamp server on ubuntu
  hosts: all
  become: yes
  vars:
    info_page_path: /var/www/html/info.php
  tasks:
    - name: check if playbook is being executed on supported OS
      ansible.builtin.fail:
        msg: "This playbook is design to work on ubuntu only"
      when: ansible_facts['distribution'] != "Ubuntu"
    - name: update packages and install apache
      ansible.builtin.package:
        name: "{{package_name}}"
        update_cache: yes
        state: present
    - name: debug apache installed
      ansible.builtin.debug:
        msg: "Installed apache server using package {{package_name}}"
    - name: install php packages
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop: "{{php_packages}}"
      notify:
        - restart apache2
    - name: debug php module installed
      ansible.builtin.debug:
        msg: "Installed php module using package {{php_packages}}"
    - name: copy info.php page
      ansible.builtin.copy:
        src: info.php
        dest: "{{info_page_path}}"
    - name: debug info.php
      ansible.builtin.debug:
        msg: "Created info.php at {{info_page_path}}"
  handlers:
    - name: restart apache2
      ansible.builtin.service:
        name: "{{package_name}}"
        state: restarted
    - name: debug apache service restart
      ansible.builtin.debug:
        msg: "Apache server restarted"