---
- name: exploring facts
  become: no
  hosts: all
  tasks:
    - name: print os
      ansible.builtin.debug:
        var: ansible_facts['os_family']
    - name: print os distribution
      ansible.builtin.debug:
        var: ansible_facts['distribution']
    - name: same info
      ansible.builtin.debug:
        var: ansible_facts['default_ipv4']